name: Update Coverage on Readme
on:
  push:
    branches:
      - main

env:
  MNEMONIC: ${{secrets.MNEMONIC}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yarn
        run: npm install yarn -g

      - name: Install deps
        run: yarn

      - name: Run tests
        run: npx jest

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        id: coverageComment
        with:
          coverage-summary-path: ./tests/coverage/coverage-summary.json
          title: Jest Coverage
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-path: ./tests/coverage/junit.xml
          coverage-path: ./tests/coverage/coverage.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          rm README.md
          awk -v awkvar='${{ steps.coverageComment.outputs.summaryHtml }}' -v RS='<!-- Jest Summary Comment:End -->\\s*' -v ORS= '{sub("<!-- Jest Summary Comment:Begin -->", awkvar)} {print}' README_template.md > README.tmp
          awk -v awkvar='${{ steps.coverageComment.outputs.junitHtml }}' -v RS='<!-- Jest Junit Comment:End -->\\s*' -v ORS= '{sub("<!-- Jest Junit Comment:Begin -->", awkvar)} {print}' README.tmp > README.tmp2
          awk -v awkvar='${{ steps.coverageComment.outputs.coverageHtml }}' -v srch1="nbsp;" -v repl1="\\&nbsp;" -v srch2="ndash;" -v repl2="\\&ndash;" -v RS='<!-- Jest Coverage Comment:End -->'  -v ORS= '{sub("<!-- Jest Coverage Comment:Begin -->", awkvar)}  { gsub(srch1,repl1,$0); gsub(srch2,repl2,$0); print $0 }' README.tmp2 > README.md
          rm README.tmp
          rm README.tmp2

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
