name: Jest coverage comment
on:
  pull_request:

env:
  MNEMONIC: ${{secrets.MNEMONIC}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yarn
        run: npm install yarn -g

      - name: Install deps
        run: yarn

      - name: Run tests
        run: npx jest | tee ./coverage.txt | tee ./coverage.txt

      - name: Jest coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./tests/coverage/coverage-summary.json
          title: Jest Coverage
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-path: ./tests/coverage/junit.xml
          coverage-path: ./coverage.txt
