# This workflow will install dependencies, create coverage tests and run Jest Coverage Comment
# For more information see: https://github.com/MishaKav/jest-coverage-comment/
name: Jest coverage comment
on:
  pull_request:

env:
  MNEMONIC: ${{secrets.MNEMONIC}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npx jest

      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./tests/coverage/coverage-summary.json
          title: Jest Coverage
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: true
          junitxml-path: ./tests/coverage/junit.xml
          coverage-path: ./tests/coverage.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i '/<!-- Jest Coverage Comment:Begin -->/,/<!-- Jest Coverage Comment:End -->/c\<!-- Jest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.summaryHtml }}\n<!-- Jest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
