name: Update Coverage on Readme
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

env:
  MNEMONIC: ${{secrets.MNEMONIC}}

jobs:
  build:
    name: main qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ALLMIGHTY_TOKEN }}

      - name: Install yarn
        run: npm install yarn -g

      - name: Install deps
        run: yarn

      - name: Run tests
        run: npx jest

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        id: coverageComment
        with:
          github-token: ${{ secrets.ALLMIGHTY_TOKEN }}
          coverage-summary-path: ./tests/coverage/coverage-summary.json
          title: Jest Coverage
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-path: ./tests/coverage/junit.xml
          coverage-path: ./tests/coverage/coverage.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          rm README.md
          awk -v input='${{ steps.coverageComment.outputs.summaryHtml }}' '{ sub(/\%/,"%",input); sub(/\&nbsp;/,"",input); sub(/nbsp;/,"",input); sub(/&ndash;/,"",input); sub(/ndash;/,"",input);  sub(/<!-- Jest Summary Comment -->/, input); print }' README_template.md > README.tmp                             
          awk -v input='${{ steps.coverageComment.outputs.junitHtml }}' '{ sub(/\%/,"%",input); sub(/\&nbsp;/,"",input); sub(/nbsp;/,"",input); sub(/&ndash;/,"",input); sub(/ndash;/,"",input);  sub(/<!-- Jest Junit Comment -->/, input); print }' README.tmp > README.tmp2
          awk -v input='${{ steps.coverageComment.outputs.coverageHtml }}' '{ sub(/\%/,"%",input); sub(/\&nbsp;/,"",input); sub(/nbsp;/,"",input); sub(/&ndash;/,"",input); sub(/ndash;/,"",input);  sub(/<!-- Jest Coverage Comment -->/, input); print }' README.tmp2 > README.md
          rm README.tmp
          rm README.tmp2

      - name: GIT Commit new README
        if: github.event_name == 'push'
        run: |
          git config --global user.name "Readme bot"
          git config --global user.email "username@users.noreply.github.com"
          git pull
          git add coverage devdist dist docs
          git commit -m Update README tests section
          git push
